# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sagittarius < Formula
  desc "Go AI agent CLI for building large projects, adminning systems, or personal assistance"
  homepage "https://github.com/undeadindustries/sagittarius"
  version "0.5.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/undeadindustries/sagittarius/releases/download/v0.5.1/sagittarius_0.5.1_darwin_amd64.tar.gz"
      sha256 "8814502a39a509dd560813b06d3b5a0f9f708c51b57132790b316a4e3dcd9e87"

      def install
        bin.install "sagittarius"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/undeadindustries/sagittarius/releases/download/v0.5.1/sagittarius_0.5.1_darwin_arm64.tar.gz"
      sha256 "0393e09d5ca4882f02c7e550a1ba187befbc5c382896950eeb35224354f5add5"

      def install
        bin.install "sagittarius"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/undeadindustries/sagittarius/releases/download/v0.5.1/sagittarius_0.5.1_linux_amd64.tar.gz"
        sha256 "a3516b17481f834470e703a17999a896f1d8212f79941a1ca7a16f59c426d0df"

        def install
          bin.install "sagittarius"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/undeadindustries/sagittarius/releases/download/v0.5.1/sagittarius_0.5.1_linux_arm64.tar.gz"
        sha256 "1cf4e6ba11570ff6302da3f294913c224c1212b8654601edb97ec64369de7775"

        def install
          bin.install "sagittarius"
        end
      end
    end
  end

  test do
    system "#{bin}/sagittarius --version"
  end
end
