# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sagittarius < Formula
  desc "Go AI agent CLI for building large projects, adminning systems, or personal assistance"
  homepage "https://github.com/undeadindustries/sagittarius"
  version "0.19.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/undeadindustries/sagittarius/releases/download/v0.19.0/sagittarius_0.19.0_darwin_amd64.tar.gz"
      sha256 "18d2eb08723c10c15bb2c08a94c48ff97f70a26c939c43e75794569d54b4cbce"

      define_method(:install) do
        bin.install "sagittarius"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/undeadindustries/sagittarius/releases/download/v0.19.0/sagittarius_0.19.0_darwin_arm64.tar.gz"
      sha256 "a6995c8d46d4767b0982d1a604567a5a0b91f7b6b080edf89c5cc0c4bc30181a"

      define_method(:install) do
        bin.install "sagittarius"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/undeadindustries/sagittarius/releases/download/v0.19.0/sagittarius_0.19.0_linux_amd64.tar.gz"
      sha256 "cad5fc16ec9bdc979a0319f393845d29cc5e3908040fe2098876b422a0d947f4"
      define_method(:install) do
        bin.install "sagittarius"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/undeadindustries/sagittarius/releases/download/v0.19.0/sagittarius_0.19.0_linux_arm64.tar.gz"
      sha256 "b90ca1652b953f21e4b8fb4ed6b1f4c1a17c60ce0d9199deb74f0e3444ecfd52"
      define_method(:install) do
        bin.install "sagittarius"
      end
    end
  end

  test do
    system "#{bin}/sagittarius --version"
  end
end
